<?php

namespace SL\PlateformBundle\Entity;

/**
 * Annee_scolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Annee_scolaireRepository extends \Doctrine\ORM\EntityRepository {

    public function getAnneeScolaire() {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.id', 'DESC');
        return $qb->getQuery()->getSingleResult();
    }

}
