<?php

namespace SL\PlateformBundle\Entity;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour obtenir la classe  en fonction de son id de user
    public function getUserClasse($id)
    {
      $query = $this->_em->createQuery('SELECT cl FROM SLPlateformBundle:Classe cl JOIN cl.eleves el JOIN el.personne p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleResult();
      return $results;
    }
    
    //requete pour obtenir les classes d'un professeur en fonction de son id de user
    public function getClasseProfesseur($id)
    {
      $query = $this->_em->createQuery('SELECT cl FROM SLPlateformBundle:Classe cl JOIN cl.professeurmatieres pm JOIN pm.professeur p JOIN p.personne ps where ps.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
     //requete pour obtenir le nombre d'eleves d'une classe donnée
    public function getEffectifClasse($id)
    {
      $query = $this->_em->createQuery('SELECT COUNT(el.id) FROM SLPlateformBundle:Eleve el JOIN el.classe cl where cl.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
    //requete pour obtenir les classes d'une ecole en fonction d'une personne
    public function getClasseDirecteur($id)
    {
      $query = $this->_em->createQuery('SELECT cl FROM SLPlateformBundle:Classe cl JOIN cl.ecole ec JOIN ec.ecolespersonnes ep JOIN ep.personne ps where ps.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour obtenir le nombre de classes d'un professeur en fonction de son id de user
    public function getNombreClasseProfesseur($id)
    {
      $query = $this->_em->createQuery('SELECT count(distinct(cl.id)) FROM SLPlateformBundle:Classe cl JOIN cl.professeurmatieres pm JOIN pm.professeur p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
    //requete pour obtenir les classes d'un professeur en fonction de son id de prof
    public function getClassesProf($id)
    {
      $query = $this->_em->createQuery('SELECT cl FROM SLPlateformBundle:Classe cl JOIN cl.professeurmatieres pm JOIN pm.professeur p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour obtenir le nombre de classes dans une ecole
    public function getNombreClasseByEcole($id)
    {
      $query = $this->_em->createQuery('SELECT count(distinct(cl.id)) FROM SLPlateformBundle:Classe cl JOIN cl.ecole ec where ec.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
    //requete pour obtenir la classe d'un composant d'emploi du temps
    public function getClasseByComposant($id)
    {
      $query = $this->_em->createQuery('SELECT cl FROM SLPlateformBundle:Classe cl JOIN cl.emploi_temps em JOIN em.composants cp where cp.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleResult();
      return $results;
    }
}
