<?php

namespace SL\PlateformBundle\Entity;

/**
 * ComposantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantRepository extends \Doctrine\ORM\EntityRepository
{
    //requete pour lister les composants en fonction du jour et de celui qui est connecté (éleve)
    public function getComposantByJour($idJ,$idU)
    {
      $query = $this->_em->createQuery('SELECT cp FROM SLPlateformBundle:Composant cp JOIN cp.jour jr JOIN cp.emploi_temps et JOIN et.classes cl JOIN cl.eleves el JOIN el.personne u where u.id=:idU and jr.id=:idJ ORDER BY cp.heureDebut ASC');
      $query->setParameter('idJ', $idJ);
      $query->setParameter('idU', $idU);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour lister les composants en fonction du jour et de celui qui est connecté (professeur)
    public function getComposantByJour2($idJ,$idU)
    {
      $query = $this->_em->createQuery('SELECT cp FROM SLPlateformBundle:Composant cp JOIN cp.emploi_temps em JOIN cp.jour jr JOIN cp.matiere ma JOIN ma.professeurmatieres pm JOIN pm.classe cl JOIN cl.emploi_temps emp JOIN pm.professeur pf JOIN pf.personne u where emp.id=em.id and u.id=:idU and jr.id=:idJ ORDER BY cp.heureDebut ASC');
      $query->setParameter('idJ', $idJ);
      $query->setParameter('idU', $idU);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour lister les composants en fonction du jour et de la classe
    public function getComposantByClasse($idJ,$idC)
    {
      $query = $this->_em->createQuery('SELECT cp FROM SLPlateformBundle:Composant cp JOIN cp.emploi_temps em JOIN cp.jour jr JOIN em.classes cl where cl.id=:idC and jr.id=:idJ ORDER BY cp.heureDebut ASC');
      $query->setParameter('idJ', $idJ);
      $query->setParameter('idC', $idC);
      $results = $query->getResult();
      return $results;
    }
    
    
}
