<?php

namespace SL\PlateformBundle\Entity;

/**
 * Cours_exoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cours_exoRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour obtenir les details du cahier de texte en fonction de la classe et de la matiere
    public function getCoursExo($matiere, $classe)
    {
      $query = $this->_em->createQuery('SELECT ce FROM SLPlateformBundle:Cours_exo ce JOIN ce.professeurmatiere pm JOIN pm.classe cl JOIN pm.matiere mt where mt.id=:idM and cl.id=:idC');
      $query->setParameter('idM', $matiere);
      $query->setParameter('idC', $classe);
      $results = $query->getResult();
      return $results;
    }
}
