<?php

namespace SL\PlateformBundle\Entity;

/**
 * Details_ctRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Details_ctRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour obtenir les details du cahier de texte en fonction de la classe et de la matiere
    public function getDetailsCt($matiere, $classe)
    {
      $query = $this->_em->createQuery('SELECT ct FROM SLPlateformBundle:Details_ct ct JOIN ct.professeurmatiere pm JOIN pm.classe cl JOIN pm.matiere mt where mt.id=:idM and cl.id=:idC ORDER BY ct.dateEnregistrement DESC');
      $query->setParameter('idM', $matiere);
      $query->setParameter('idC', $classe);
      $results = $query->getResult();
      return $results;
    }
    
}
