<?php

namespace SL\PlateformBundle\Entity;

/**
 * EcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleRepository extends \Doctrine\ORM\EntityRepository
{
    //recuperer l'ecole en fction du connecté
    public function getEcoleByUser($id)
    {
      $query = $this->_em->createQuery('SELECT ec FROM SLPlateformBundle:Ecole ec JOIN ec.ecolespersonnes ep JOIN ep.personne u where u.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleResult();
      return $results;
    }
}
