<?php

namespace SL\PlateformBundle\Entity;

/**
 * EcolePersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcolePersonneRepository extends \Doctrine\ORM\EntityRepository
{
}
