<?php

namespace SL\PlateformBundle\Entity;

/**
 * EcoleProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleProfesseurRepository extends \Doctrine\ORM\EntityRepository
{
      //requete pour obtenir les lignes du prof en fct de l'ecole
    public function getProfEcol($idP,$idU)
    {
      $query = $this->_em->createQuery('SELECT ep FROM SLPlateformBundle:EcoleProfesseur ep JOIN ep.professeur p JOIN ep.ecole e JOIN e.ecolespersonnes ecp JOIN ecp.personne ps where ps.id=:idU and p.id=:idP');
      $query->setParameter('idP', $idP);
      $query->setParameter('idU', $idU);
      $results = $query->getSingleResult();
      return $results;
    }
}
