<?php

namespace SL\PlateformBundle\Entity;

/**
 * EducateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducateurRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour lister les professeurs en focntion de l'ecole de celui qui est connecté
    public function getEducateursBySchool($id)
    {
      $query = $this->_em->createQuery('SELECT ed FROM SLPlateformBundle:Educateur ed JOIN ed.personne ps JOIN ps.ecolespersonnes epp JOIN epp.ecole e JOIN e.ecolespersonnes ep JOIN ep.personne u where u.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
}
