<?php

namespace SL\PlateformBundle\Entity;

/**
 * EleveExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveExamenRepository extends \Doctrine\ORM\EntityRepository
{
        //requete pour obtenir les notes d'un élève a un examen
    public function getElevesByExamen($idEx,$idEl)
    {
      $query = $this->_em->createQuery('SELECT ee FROM SLPlateformBundle:EleveExamen ee JOIN ee.examen ex JOIN ee.eleve el where el.id=:idEl and ex.id=:idEx');
      $query->setParameter('idEx', $idEx);
      $query->setParameter('idEl', $idEl);
      $results = $query->getResult();
      return $results;
    }
}
