<?php

namespace SL\PlateformBundle\Entity;

/**
 * EleveCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
