<?php

namespace SL\PlateformBundle\Entity;

/**
 * Emploi_tempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Emploi_tempsRepository extends \Doctrine\ORM\EntityRepository
{
}
