<?php

namespace SL\PlateformBundle\Entity;

/**
 * ExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends \Doctrine\ORM\EntityRepository
{
           //requete pour lister les examens d'une ecole dans cette année
    public function getExamens($idA,$idE)
    {
      $query = $this->_em->createQuery('SELECT ex FROM SLPlateformBundle:Examen ex JOIN ex.ecole ec JOIN ex.annee_scolaire an where an.id=:idA and ec.id=:idE');
       $query->setParameter('idE', $idE);
      $query->setParameter('idA', $idA);
      $results = $query->getResult();
      return $results;
    }
    
      //requete pour lister les examens d'une ecole
    public function getExamensBySchool($id)
    {
      $query = $this->_em->createQuery('SELECT ex FROM SLPlateformBundle:Examen ex JOIN ex.ecole ec where ec.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
        //requete pour lister les examens d'un eleve  dans cette année
    public function getExamenByUser($idA,$idE)
    {
      $query = $this->_em->createQuery('SELECT ex FROM SLPlateformBundle:Examen ex JOIN ex.eleveexamens ee JOIN ee.eleve el JOIN el.personne ps JOIN ex.annee_scolaire an where an.id=:idA and ps.id=:idE');
       $query->setParameter('idE', $idE);
      $query->setParameter('idA', $idA);
      $results = $query->getResult();
      return $results;
    }
    
}
