<?php

namespace SL\PlateformBundle\Entity;

/**
 * JourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourRepository extends \Doctrine\ORM\EntityRepository
{
        //requete pour lister les jours de l'emploi du temps d'un eleve en fonction de son id de user
    public function getJoursByEleve($id)
    {
      $query = $this->_em->createQuery('SELECT jr FROM SLPlateformBundle:Jour jr JOIN jr.composants c JOIN c.emploi_temps em JOIN em.classes cl JOIN cl.eleves el JOIN el.personne u where u.id=:id order by jr.id ASC');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
       //requete pour lister les jours qui ont des composants
    public function getJoursOuvrables()
    {
      $query = $this->_em->createQuery('SELECT jr FROM SLPlateformBundle:Jour jr JOIN jr.composants c order by jr.id ASC');
      $results = $query->getResult();
      return $results;
    }
    
       //requete pour lister les jours qui ont des composants
    public function getJours()
    {
      $query = $this->_em->createQuery('SELECT jr FROM SLPlateformBundle:Jour jr order by jr.id ASC');
      $results = $query->getResult();
      return $results;
    }
}
