<?php

namespace SL\PlateformBundle\Entity;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
      //requete pour lister les matieres d'une classe  en fonction de son id de user
    public function getMatieresByUser($id)
    {
      $query = $this->_em->createQuery('SELECT mt FROM SLPlateformBundle:Matiere mt JOIN mt.professeurmatieres pm JOIN pm.classe cl JOIN cl.eleves el JOIN el.personne p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
       //requete pour obtenir la liste des matieres qu'un professeur fait dans une classe
    public function getMatiereProf($idC,$idP)
    {
      $query = $this->_em->createQuery('SELECT mt FROM SLPlateformBundle:Matiere mt JOIN mt.professeurmatieres pm JOIN pm.classe cl JOIN pm.professeur pf JOIN pf.personne ps where cl.id=:idC and ps.id=:idP');
      $query->setParameter('idC', $idC);
      $query->setParameter('idP', $idP);
      $results = $query->getResult();
      return $results;
    }
    
       //requete pour obtenir la liste des matieres d'une classe
    public function getMatiereByClasse($idC)
    {
      $query = $this->_em->createQuery('SELECT mt FROM SLPlateformBundle:Matiere mt JOIN mt.professeurmatieres pm JOIN pm.classe cl where cl.id=:idC');
      $query->setParameter('idC', $idC);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour obtenir le nombre de matiere d'un professeur en fonction de son id de user
    public function getNombreMatiereProfesseur($id)
    {
      $query = $this->_em->createQuery('SELECT count(distinct(mt.id)) FROM SLPlateformBundle:Matiere mt JOIN mt.professeurmatieres pm JOIN pm.professeur p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
}
