<?php

namespace SL\PlateformBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour lister les messages recus d'un user
    public function getSendMsgByUser($id)
    {
      $query = $this->_em->createQuery('SELECT mp FROM SLPlateformBundle:Message mp JOIN mp.emetteur em where em.id=:id order by mp.dateMessage DESC');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
     //requete pour recuperer le nombre de messages envoyées
    public function getNbreSendMsgByUser($id)
    {
      $query = $this->_em->createQuery('SELECT count(mp.id) FROM SLPlateformBundle:Message mp JOIN mp.emetteur em where em.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
}
