<?php

namespace SL\PlateformBundle\Entity;

/**
 * Messages_personneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Messages_personneRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour lister les messages recus d'un user
    public function getReceivedMsgByUser($id)
    {
      $query = $this->_em->createQuery('SELECT mp FROM SLPlateformBundle:Messages_personne mp JOIN mp.message m JOIN mp.personne p where p.id=:id order by m.dateMessage DESC');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour avoir le nombre de messages non lu
    public function getNbombreMsgNonLuByUser($id)
    {
      $query = $this->_em->createQuery('SELECT count(mp.id) FROM SLPlateformBundle:Messages_personne mp JOIN mp.personne p where p.id=:id and mp.statut=false');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
    //requete pour avoir le nombre total de messages
    public function getNbombreMsgTotalByUser($id)
    {
      $query = $this->_em->createQuery('SELECT count(mp.id) FROM SLPlateformBundle:Messages_personne mp JOIN mp.personne p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
    //requete pour lister les messages recus d'un user
    public function getLastReceivedMsgByUser($id)
    {
      $query = $this->_em->createQuery('SELECT mp FROM SLPlateformBundle:Messages_personne mp JOIN mp.message m JOIN mp.personne p where p.id=:id and mp.statut=false order by m.dateMessage DESC');
      $query->setParameter('id', $id);
      $query->setFirstResult(0);
      $query->setMaxResults(5);
      $results = $query->getResult();
      return $results;
    }
}
