<?php

namespace SL\PlateformBundle\Entity;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends \Doctrine\ORM\EntityRepository
{
    //requete pour  recuperer les notes de l'eleve en fonction de sa matiere
    public function getNotesByUserAndMatiere($idU,$idM)
    {
      $query = $this->_em->createQuery('SELECT n FROM SLPlateformBundle:Notes n JOIN n.matiere mt JOIN n.eleve el where el.id=:idU and mt.id=:idM');
      $query->setParameter('idU', $idU);
      $query->setParameter('idM', $idM);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour  recuperer la plus forte note en devoir
    public function getForteNote($id)
    {
      $query = $this->_em->createQuery('SELECT MAX(n.note) FROM SLPlateformBundle:Notes n JOIN n.type_note tn JOIN n.eleve el JOIN el.personne ps where ps.id=:id and tn.libelle=:type');
      $query->setParameter('id', $id);
      $query->setParameter('type', 'Devoir');
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
     //requete pour  recuperer la plus faible note en devoir
    public function getFaibleNote($id)
    {
     $query = $this->_em->createQuery('SELECT MIN(n.note) FROM SLPlateformBundle:Notes n JOIN n.type_note tn JOIN n.eleve el JOIN el.personne ps where ps.id=:id and tn.libelle=:type');
      $query->setParameter('id', $id);
      $query->setParameter('type', 'Devoir');
      $results = $query->getSingleScalarResult();
      return $results;
    }
}
