<?php

namespace SL\PlateformBundle\Entity;

/**
 * ProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour lister les professeurs en focntion de l'ecole de celui qui est connecté
    public function getProfesseursBySchool($id)
    {
      $query = $this->_em->createQuery('SELECT pf FROM SLPlateformBundle:Professeur pf JOIN pf.ecoleprofesseurs ec JOIN ec.ecole e JOIN e.ecolespersonnes ep JOIN ep.personne u where u.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour obtenir le nombre de professeurs dans une ecole
    public function getNombreProfByEcole($id)
    {
      $query = $this->_em->createQuery('SELECT count(distinct(pf.id)) FROM SLPlateformBundle:Professeur pf JOIN pf.ecoleprofesseurs ep JOIN ep.ecole ec where ec.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleScalarResult();
      return $results;
    }
    
     //recuperer la liste des professeurs-matieres d'une classe en fonction de l'id user (élève)
    public function getProfesseurMatiere($idM,$idC)
    {
      $query = $this->_em->createQuery('SELECT pf FROM SLPlateformBundle:Professeur pf JOIN pf.professeurmatieres pm JOIN pm.matiere m JOIN pm.classe cl where m.id=:idM and cl.id=:idC');
      $query->setParameter('idM', $idM);
      $query->setParameter('idC', $idC);
      $results = $query->getSingleResult();
      return $results;
    }
}
