<?php

namespace SL\PlateformBundle\Entity;

/**
 * ProfesseurMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurMatiereRepository extends \Doctrine\ORM\EntityRepository
{
    //recuperer la liste des professeurs-matieres d'une classe en fonction de l'id user (élève)
    public function getProfesseurMatiereByEleve($id)
    {
      $query = $this->_em->createQuery('SELECT pfm FROM SLPlateformBundle:ProfesseurMatiere pfm JOIN pfm.classe cl JOIN cl.eleves el JOIN el.personne u where u.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
    //recuperer le "professeurmatiere" courant c'est a dire le professeur - la classe - et la matiere
    public function getProfesseurMatiere($idProf,$idMat,$idClass)
    {
      $query = $this->_em->createQuery('SELECT pfm FROM SLPlateformBundle:ProfesseurMatiere pfm JOIN pfm.classe cl JOIN pfm.matiere mt JOIN pfm.professeur pf JOIN  pf.personne p where p.id=:idProf and cl.id=:idClass and mt.id=:idMat');
      $query->setParameter('idProf', $idProf);
      $query->setParameter('idClass', $idClass);
      $query->setParameter('idMat', $idMat);
      $results = $query->getSingleResult();
      return $results;
    }
    
     //requete pour obtenir les lignes du prof en fct de l'ecole
    public function getProfMatiere($idP)
    {
      $query = $this->_em->createQuery('SELECT pm FROM SLPlateformBundle:ProfesseurMatiere pm JOIN pm.professeur p where p.id=:idP');
      $query->setParameter('idP', $idP);
      $results = $query->getResult();
      return $results;
    }
     //requete pour obtenir les lignes du prof en fct de la Classe
    public function getAttributionByClasse($idC,$idP)
    {
      $query = $this->_em->createQuery('SELECT pm FROM SLPlateformBundle:ProfesseurMatiere pm JOIN pm.professeur p JOIN pm.classe c where p.id=:idP and c.id=:idC');
      $query->setParameter('idP', $idP);
      $query->setParameter('idC', $idC);
      $results = $query->getResult();
      return $results;
    }
    
}
