<?php

namespace SL\PlateformBundle\Entity;

/**
 * ReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementRepository extends \Doctrine\ORM\EntityRepository
{
       //requete pour lister les reglements de la classe concernee
    public function getReglements($id)
    {
      $query = $this->_em->createQuery('SELECT gl FROM SLPlateformBundle:Reglement gl JOIN gl.classe cl JOIN gl.type_reglement tr JOIN gl.mois ms where cl.id=:id and tr.libelle=:lib');
      $query->setParameter('id', $id);
      $query->setParameter('lib', "versements");
      $results = $query->getResult();
      return $results;
    }
    
     //requete pour lister les reglements de la classe concernee
    public function getFrais($id)
    {
      $query = $this->_em->createQuery('SELECT gl FROM SLPlateformBundle:Reglement gl JOIN gl.classe cl JOIN gl.type_reglement tr JOIN gl.mois ms where cl.id=:id and tr.libelle=:lib');
      $query->setParameter('id', $id);
      $query->setParameter('lib', "frais");
      $results = $query->getResult();
      return $results;
    }
}
