<?php

namespace SL\PlateformBundle\Entity;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends \Doctrine\ORM\EntityRepository
{
     //requete pour obtenir le statut  en fonction de son id de user
    public function getUserStatut($id)
    {
      $query = $this->_em->createQuery('SELECT st FROM SLPlateformBundle:Statut st JOIN st.ecolespersonnes ep JOIN ep.personne p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getSingleResult();
      return $results;
    }
}
