<?php

namespace SL\PlateformBundle\Entity;

/**
 * Type_details_crRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_details_crRepository extends \Doctrine\ORM\EntityRepository
{
        //requete pour lister les types details de carnet de correspondance d'un eleve en fonction de son id de user
    public function getTypeDetailsByUser($id)
    {
      $query = $this->_em->createQuery('SELECT tp FROM SLPlateformBundle:Type_details_cr tp JOIN tp.details_crs cr JOIN cr.eleve el JOIN el.personne p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
    
    //requete pour lister les types details de carnet de correspondance d'un eleve en fonction de son id de eleve
    public function getTypeDetailsByUser2($id)
    {
      $query = $this->_em->createQuery('SELECT tp FROM SLPlateformBundle:Type_details_cr tp JOIN tp.details_crs cr JOIN cr.eleve el where el.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
}
