<?php

namespace SL\PlateformBundle\Entity;

/**
 * Type_reglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_reglementRepository extends \Doctrine\ORM\EntityRepository
{
}
