<?php

namespace SL\PlateformBundle\Entity;

/**
 * Type_noteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_noteRepository extends \Doctrine\ORM\EntityRepository
{
       //requete pour lister les types de notes d'un eleve en fonction de son id de user
    public function getTypeNotesByUser($id)
    {
      $query = $this->_em->createQuery('SELECT tn FROM SLPlateformBundle:Type_note tn JOIN tn.notes nt JOIN nt.eleve el JOIN el.personne p where p.id=:id');
      $query->setParameter('id', $id);
      $results = $query->getResult();
      return $results;
    }
}
